import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/app/globals.css"
import ProfileNavigationBar from "@/components/ProfileNavigationBar"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import SidebarNavigation from "@/components/SidebarNavigation"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ProfileNavigationBar />
				<SidebarNavigation>{children}</SidebarNavigation>
			</body>
		</html>
	)
}
